version: v2.7.0
plugins:
  - module: "github.com/google/go-github/v81/tools/fmtpercentv"
    path: ./tools/fmtpercentv
  - module: "github.com/google/go-github/v81/tools/sliceofpointers"
    path: ./tools/sliceofpointers
  - module: "github.com/google/go-github/v81/tools/structfield"
    path: ./tools/structfield
