version: v2.2.2
plugins:
  - module: "github.com/google/go-github/v75/tools/gogithub"
    path: ./tools/gogithub
  - module: "github.com/google/go-github/v75/tools/fmtpercentv"
    path: ./tools/fmtpercentv
