version: v2.2.2
plugins:
  - module: "github.com/google/go-github/v75/tools/fmtpercentv"
    path: ./tools/fmtpercentv
  - module: "github.com/google/go-github/v75/tools/jsonfieldname"
    path: ./tools/jsonfieldname
  - module: "github.com/google/go-github/v75/tools/sliceofpointers"
    path: ./tools/sliceofpointers
