run:
  build-tags:
    - integration
  timeout: 10m
linters:
  enable:
    - dogsled
    - dupl
    - gocritic
    - godot
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - perfsprint
    - paralleltest
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
linters-settings:
  gocritic:
    disable-all: true
    enabled-checks:
      - commentFormatting
  gosec:
    excludes:
      # duplicates errcheck
      - G104
      # int(os.Stdin.Fd())
      - G115
  perfsprint:
    errorf: true
    strconcat: false
issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - unparam
        - gosec
        - dogsled
      path: _test\.go

    # We need to pass nil Context in order to test DoBare erroring on nil ctx.
    - linters: [ staticcheck ]
      text: 'SA1012: do not pass a nil Context'
      path: _test\.go

    # We need to use sha1 for validating signatures
    - linters: [ gosec ]
      text: 'G505: Blocklisted import crypto/sha1: weak cryptographic primitive'

    # This is adapted from golangci-lint's default exclusions. It disables linting for error checks on
    # os.RemoveAll, fmt.Fprint*, fmt.Scanf, and any function ending in "Close".
    - linters: [ errcheck ]
      text: Error return value of .(.*Close|fmt\.Fprint.*|fmt\.Scanf|os\.Remove(All)?). is not checked

    # We don't care about file inclusion via variable in examples or internal tools.
    - linters: [ gosec ]
      text: 'G304: Potential file inclusion via variable'
      path: '^(example|tools)\/'

    # We don't run parallel integration tests
    - linters: [ paralleltest, tparallel ]
      path: '^test/integration'

    # Because fmt.Sprint(reset.Unix())) is more readable than strconv.FormatInt(reset.Unix(), 10).
    - linters: [ perfsprint]
      text: 'fmt.Sprint.* can be replaced with faster strconv.FormatInt'
