#!/bin/sh
#/ golangci-lint installs golangci-lint and runs it with the given arguments.

set -e

GOLANGCI_LINT_VERSION="v1.54.2"

REPO_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")/.." && pwd -P)"
export GOBIN="$REPO_DIR"/bin
mkdir -p "$GOBIN"

install_golangci_lint() {
  if [ -f "$GOBIN"/golangci-lint ]; then
    if "$GOBIN"/golangci-lint --version | grep -q "$GOLANGCI_LINT_VERSION"; then
      return
    fi
  fi
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}
}

install_golangci_lint
exec "$GOBIN"/golangci-lint "$@"
