// Copyright 2025 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github

import (
	"context"
	"fmt"
)

// The URIs that are used to indicate the namespaces of the SCIM schemas
const SCIMSchemasURINamespacesGroups string = "urn:ietf:params:scim:schemas:core:2.0:Group"
const SCIMSchemasURINamespacesListResponse string = "urn:ietf:params:scim:api:messages:2.0:ListResponse"

// SCIMEnterpriseGroupAttributes represents supported SCIM Enterprise group attributes.
// GitHub API docs:https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/scim#supported-scim-group-attributes
type SCIMEnterpriseGroupAttributes struct {
	DisplayName *string                           `json:"displayName,omitempty"` // Human-readable name for a group.
	Members     []*SCIMEnterpriseDisplayReference `json:"members,omitempty"`     // List of members who are assigned to the group in SCIM provider
	ExternalID  *string                           `json:"externalId,omitempty"`  // This identifier is generated by a SCIM provider. Must be unique per user.
	// Bellow: Only populated as a result of calling SetSCIMInformationForProvisionedEnterpriseGroup:
	Schemas []string            `json:"schemas,omitempty"` // The URIs that are used to indicate the namespaces of the SCIM schemas.
	ID      *string             `json:"id,omitempty"`      // The internally generated id for the group object.
	Meta    *SCIMEnterpriseMeta `json:"meta,omitempty"`    // The metadata associated with the creation/updates to the group.
}

// SCIMEnterpriseDisplayReference represents a JSON SCIM (System for Cross-domain Identity Management) resource.
type SCIMEnterpriseDisplayReference struct {
	Value   string  `json:"value"` // The local unique identifier for the member
	Ref     string  `json:"$ref"`
	Display *string `json:"display,omitempty"` // The display name associated with the member
}

// SCIMEnterpriseMeta represents metadata about the SCIM resource.
type SCIMEnterpriseMeta struct {
	ResourceType *string    `json:"resourceType"`           // A type of a resource (`User` or `Group`).
	Created      *Timestamp `json:"created,omitempty"`      // A date and time when the user was created.
	LastModified *Timestamp `json:"lastModified,omitempty"` // A date and time when the user was last modified.
	Location     *string    `json:"location,omitempty"`     // A URL location of an object
}

// SCIMEnterpriseGroups represents the result of calling ListProvisionedSCIMGroupsForEnterprises.
type SCIMEnterpriseGroups struct {
	Schemas      []string                         `json:"schemas"`
	TotalResults *int                             `json:"totalResults"`
	Resources    []*SCIMEnterpriseGroupAttributes `json:"Resources"`
	StartIndex   *int                             `json:"startIndex"`
	ItemsPerPage *int                             `json:"itemsPerPage"`
}

// ListProvisionedSCIMGroupsForEnterpriseOptions represents query parameters for ListProvisionedSCIMGroupsForEnterprise.
//
// GitHub API docs: https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/scim#list-provisioned-scim-groups-for-an-enterprise--parameters
type ListProvisionedSCIMGroupsForEnterpriseOptions struct {
	// If specified, only results that match the specified filter will be returned. Multiple filters are not supported.
	// Possible filters are `externalId`, id, and `displayName`. For example,`?filter=externalId eq "9138790-10932-109120392-12321"`.
	Filter *string `url:"filter,omitempty"`
	// Excludes the specified attribute from being returned in the results. Using this parameter can speed up response time.
	ExcludedAttributes *string `url:"excludedAttributes,omitempty"`
	// Excludes the specified attribute from being returned in the results. Using this parameter can speed up response time.
	// Default: 1.
	StartIndex *int `url:"startIndex,omitempty"`
	// Used for pagination: the number of results to return per page.
	// Default: 30.
	Count *int `url:"count,omitempty"`
}

// ListProvisionedSCIMGroupsForEnterprise lists provisioned SCIM groups in an enterprise.
// GitHub API docs: https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/scim#list-provisioned-scim-groups-for-an-enterprise
//
//meta:operation GET /scim/v2/enterprises/{enterprise}/Groups
func (s *EnterpriseService) ListProvisionedSCIMGroupsForEnterprise(ctx context.Context, enterprise string, opts *ListProvisionedSCIMGroupsForEnterpriseOptions) (*SCIMEnterpriseGroupAttributes, *Response, error) {
	u := fmt.Sprintf("scim/v2/enterprises/%v/Groups", enterprise)
	u, err := addOptions(u, opts)
	if err != nil {
		return nil, nil, err
	}

	req, err := s.client.NewRequest("GET", u, nil)
	if err != nil {
		return nil, nil, err
	}

	groups := new(SCIMEnterpriseGroupAttributes)
	resp, err := s.client.Do(ctx, req, groups)
	if err != nil {
		return nil, resp, err
	}

	return groups, resp, nil
}
