// Code generated by gen-iterators; DO NOT EDIT.
// Instead, please run "go generate ./..." as described here:
// https://github.com/google/go-github/blob/master/CONTRIBUTING.md#submitting-a-patch

// Copyright 2026 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package github

import (
	"fmt"
	"net/http"
	"testing"
)

func TestActivityService_ListEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListEventsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsForOrganizationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListEventsForOrganizationIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsForRepoNetworkIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListEventsForRepoNetworkIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsPerformedByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListEventsPerformedByUserIter(t.Context(), "", false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsReceivedByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListEventsReceivedByUserIter(t.Context(), "", false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListIssueEventsForRepositoryIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListIssueEventsForRepositoryIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListNotificationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListNotificationsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListRepositoryEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListRepositoryEventsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListRepositoryNotificationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListRepositoryNotificationsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListStargazersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListStargazersIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListStarredIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListStarredIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListUserEventsForOrganizationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListUserEventsForOrganizationIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListWatchedIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListWatchedIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListWatchersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Activity.ListWatchersIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListInstallationRequestsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Apps.ListInstallationRequestsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Apps.ListInstallationsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListUserInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `{"installations": []}`)
	})

	// Call iterator with zero values
	iter := client.Apps.ListUserInstallationsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestChecksService_ListCheckRunAnnotationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Checks.ListCheckRunAnnotationsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListAcceptedAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Classroom.ListAcceptedAssignmentsIter(t.Context(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListClassroomAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Classroom.ListClassroomAssignmentsIter(t.Context(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListClassroomsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Classroom.ListClassroomsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertInstancesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertInstancesIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertsForOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertsForOrgIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertsForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertsForRepoIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAnalysesForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.CodeScanning.ListAnalysesForRepoIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestDependabotService_ListOrgAlertsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Dependabot.ListOrgAlertsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestDependabotService_ListRepoAlertsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Dependabot.ListRepoAlertsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppAccessibleOrganizationRepositoriesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListAppAccessibleOrganizationRepositoriesIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppInstallableOrganizationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListAppInstallableOrganizationsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListAppInstallationsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListAssignmentsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListOrganizationCustomPropertyValuesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListOrganizationCustomPropertyValuesIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListRepositoriesForOrgAppInstallationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListRepositoriesForOrgAppInstallationIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListTeamMembersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListTeamMembersIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Enterprise.ListTeamsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListAllIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListCommentsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListCommitsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListForksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListForksIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListStarredIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Gists.ListStarredIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListIter(t.Context(), false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListAssigneesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListAssigneesIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListByOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListByOrgIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListByRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListByRepoIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListCommentsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIssueEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListIssueEventsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIssueTimelineIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListIssueTimelineIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListLabelsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsByIssueIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListLabelsByIssueIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsForMilestoneIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListLabelsForMilestoneIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListMilestonesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListMilestonesIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListRepositoryEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Issues.ListRepositoryEventsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListMarketplacePurchasesForUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Marketplace.ListMarketplacePurchasesForUserIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListPlanAccountsForPlanIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Marketplace.ListPlanAccountsForPlanIter(t.Context(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListPlansIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Marketplace.ListPlansIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMigrationService_ListMigrationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Migrations.ListMigrationsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMigrationService_ListUserMigrationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Migrations.ListUserMigrationsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListAllIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListBlockedUsersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListBlockedUsersIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListCredentialAuthorizationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListCredentialAuthorizationsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListCustomPropertyValuesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListCustomPropertyValuesIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListFailedOrgInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListFailedOrgInvitationsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListFineGrainedPersonalAccessTokensIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListFineGrainedPersonalAccessTokensIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListHooksIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListMembersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListMembersIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOrgInvitationTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListOrgInvitationTeamsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOrgMembershipsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListOrgMembershipsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOutsideCollaboratorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListOutsideCollaboratorsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListPackagesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListPackagesIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListPendingOrgInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListPendingOrgInvitationsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListTeamsAssignedToOrgRoleIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListTeamsAssignedToOrgRoleIter(t.Context(), "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListUsersAssignedToOrgRoleIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Organizations.ListUsersAssignedToOrgRoleIter(t.Context(), "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListCommentsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListCommitsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListFilesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListFilesIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListPullRequestsWithCommitIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListPullRequestsWithCommitIter(t.Context(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListReviewCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListReviewCommentsIter(t.Context(), "", "", 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListReviewsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.PullRequests.ListReviewsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListCommentReactionsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListIssueCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListIssueCommentReactionsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListIssueReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListIssueReactionsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListPullRequestCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListPullRequestCommentReactionsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListReleaseReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListReleaseReactionsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListTeamDiscussionCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListTeamDiscussionCommentReactionsIter(t.Context(), 0, 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListTeamDiscussionReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Reactions.ListTeamDiscussionReactionsIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListAutolinksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListAutolinksIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListBranchesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListBranchesIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByAuthenticatedUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListByAuthenticatedUserIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListByOrgIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListByUserIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCollaboratorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListCollaboratorsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListCommentsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommitCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListCommitCommentsIter(t.Context(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListCommitsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListContributorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListContributorsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListDeploymentStatusesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListDeploymentStatusesIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListDeploymentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListDeploymentsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListForksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListForksIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListHooksIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListInvitationsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListKeysIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListPagesBuildsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListPagesBuildsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListPreReceiveHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListPreReceiveHooksIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListReleaseAssetsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListReleaseAssetsIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListReleasesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListReleasesIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListStatusesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListStatusesIter(t.Context(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListTagsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListTagsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Repositories.ListTeamsIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForEnterpriseIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForEnterpriseIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForOrgIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForRepoIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListLocationsForAlertIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.SecretScanning.ListLocationsForAlertIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSubIssueService_ListByIssueIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.SubIssue.ListByIssueIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListChildTeamsByParentIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListChildTeamsByParentIDIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListChildTeamsByParentSlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListChildTeamsByParentSlugIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListCommentsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListCommentsByIDIter(t.Context(), 0, 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListCommentsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListCommentsBySlugIter(t.Context(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListDiscussionsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListDiscussionsByIDIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListDiscussionsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListDiscussionsBySlugIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListPendingTeamInvitationsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListPendingTeamInvitationsByIDIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListPendingTeamInvitationsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListPendingTeamInvitationsBySlugIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamMembersByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListTeamMembersByIDIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamMembersBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListTeamMembersBySlugIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamReposByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListTeamReposByIDIter(t.Context(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamReposBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListTeamReposBySlugIter(t.Context(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListTeamsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListUserTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Teams.ListUserTeamsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListAllIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListBlockedUsersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListBlockedUsersIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListEmailsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListEmailsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListFollowersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListFollowersIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListFollowingIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListFollowingIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListGPGKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListGPGKeysIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListInvitationsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListKeysIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListPackagesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListPackagesIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListSSHSigningKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListSSHSigningKeysIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListSocialAccountsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListSocialAccountsIter(t.Context(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListUserSocialAccountsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	// Call iterator with zero values
	iter := client.Users.ListUserSocialAccountsIter(t.Context(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}
