// Copyright 2025 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-iterators; DO NOT EDIT.

package github

import (
	"context"
	"fmt"
	"net/http"
	"testing"
)

func TestActivityService_ListEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListEventsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsForOrganizationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListEventsForOrganizationIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsForRepoNetworkIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListEventsForRepoNetworkIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsPerformedByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListEventsPerformedByUserIter(context.Background(), "", false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListEventsReceivedByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListEventsReceivedByUserIter(context.Background(), "", false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListIssueEventsForRepositoryIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListIssueEventsForRepositoryIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListNotificationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListNotificationsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListRepositoryEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListRepositoryEventsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListRepositoryNotificationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListRepositoryNotificationsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListStargazersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListStargazersIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListStarredIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListStarredIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListUserEventsForOrganizationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListUserEventsForOrganizationIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListWatchedIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListWatchedIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestActivityService_ListWatchersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Activity.ListWatchersIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListInstallationRequestsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Apps.ListInstallationRequestsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Apps.ListInstallationsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestAppsService_ListUserInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `{"installations": []}`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Apps.ListUserInstallationsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestChecksService_ListCheckRunAnnotationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Checks.ListCheckRunAnnotationsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListAcceptedAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Classroom.ListAcceptedAssignmentsIter(context.Background(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListClassroomAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Classroom.ListClassroomAssignmentsIter(context.Background(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestClassroomService_ListClassroomsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Classroom.ListClassroomsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertInstancesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertInstancesIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertsForOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertsForOrgIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAlertsForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.CodeScanning.ListAlertsForRepoIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestCodeScanningService_ListAnalysesForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.CodeScanning.ListAnalysesForRepoIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestDependabotService_ListOrgAlertsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Dependabot.ListOrgAlertsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestDependabotService_ListRepoAlertsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Dependabot.ListRepoAlertsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppAccessibleOrganizationRepositoriesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListAppAccessibleOrganizationRepositoriesIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppInstallableOrganizationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListAppInstallableOrganizationsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAppInstallationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListAppInstallationsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListAssignmentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListAssignmentsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListOrganizationCustomPropertyValuesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListOrganizationCustomPropertyValuesIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListRepositoriesForOrgAppInstallationIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListRepositoriesForOrgAppInstallationIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListTeamMembersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListTeamMembersIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestEnterpriseService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Enterprise.ListTeamsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListAllIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListCommentsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListCommitsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListForksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListForksIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGistsService_ListStarredIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Gists.ListStarredIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestGitService_ListMatchingRefsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Git.ListMatchingRefsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListIter(context.Background(), false, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListAssigneesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListAssigneesIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListByOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListByOrgIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListByRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListByRepoIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListCommentsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIssueEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListIssueEventsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListIssueTimelineIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListIssueTimelineIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListLabelsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsByIssueIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListLabelsByIssueIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListLabelsForMilestoneIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListLabelsForMilestoneIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListMilestonesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListMilestonesIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestIssuesService_ListRepositoryEventsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Issues.ListRepositoryEventsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListMarketplacePurchasesForUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Marketplace.ListMarketplacePurchasesForUserIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListPlanAccountsForPlanIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Marketplace.ListPlanAccountsForPlanIter(context.Background(), 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMarketplaceService_ListPlansIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Marketplace.ListPlansIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMigrationService_ListMigrationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Migrations.ListMigrationsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestMigrationService_ListUserMigrationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Migrations.ListUserMigrationsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListAllIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListBlockedUsersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListBlockedUsersIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListCredentialAuthorizationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListCredentialAuthorizationsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListCustomPropertyValuesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListCustomPropertyValuesIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListFailedOrgInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListFailedOrgInvitationsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListFineGrainedPersonalAccessTokensIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListFineGrainedPersonalAccessTokensIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListHooksIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListMembersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListMembersIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOrgInvitationTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListOrgInvitationTeamsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOrgMembershipsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListOrgMembershipsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListOutsideCollaboratorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListOutsideCollaboratorsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListPackagesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListPackagesIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListPendingOrgInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListPendingOrgInvitationsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListTeamsAssignedToOrgRoleIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListTeamsAssignedToOrgRoleIter(context.Background(), "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestOrganizationsService_ListUsersAssignedToOrgRoleIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Organizations.ListUsersAssignedToOrgRoleIter(context.Background(), "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListCommentsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListCommitsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListFilesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListFilesIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListPullRequestsWithCommitIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListPullRequestsWithCommitIter(context.Background(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListReviewCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListReviewCommentsIter(context.Background(), "", "", 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestPullRequestsService_ListReviewsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.PullRequests.ListReviewsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListCommentReactionsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListIssueCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListIssueCommentReactionsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListIssueReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListIssueReactionsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListPullRequestCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListPullRequestCommentReactionsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListReleaseReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListReleaseReactionsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListTeamDiscussionCommentReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListTeamDiscussionCommentReactionsIter(context.Background(), 0, 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestReactionsService_ListTeamDiscussionReactionsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Reactions.ListTeamDiscussionReactionsIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListAutolinksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListAutolinksIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListBranchesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListBranchesIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByAuthenticatedUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListByAuthenticatedUserIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListByOrgIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListByUserIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListByUserIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCollaboratorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListCollaboratorsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListCommentsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommitCommentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListCommitCommentsIter(context.Background(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListCommitsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListCommitsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListContributorsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListContributorsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListDeploymentStatusesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListDeploymentStatusesIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListDeploymentsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListDeploymentsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListForksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListForksIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListHooksIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListInvitationsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListKeysIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListPagesBuildsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListPagesBuildsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListPreReceiveHooksIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListPreReceiveHooksIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListReleaseAssetsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListReleaseAssetsIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListReleasesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListReleasesIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListStatusesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListStatusesIter(context.Background(), "", "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListTagsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListTagsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestRepositoriesService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Repositories.ListTeamsIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForEnterpriseIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForEnterpriseIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForOrgIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForOrgIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListAlertsForRepoIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.SecretScanning.ListAlertsForRepoIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSecretScanningService_ListLocationsForAlertIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.SecretScanning.ListLocationsForAlertIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestSubIssueService_ListByIssueIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.SubIssue.ListByIssueIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListChildTeamsByParentIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListChildTeamsByParentIDIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListChildTeamsByParentSlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListChildTeamsByParentSlugIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListCommentsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListCommentsByIDIter(context.Background(), 0, 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListCommentsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListCommentsBySlugIter(context.Background(), "", "", 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListDiscussionsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListDiscussionsByIDIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListDiscussionsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListDiscussionsBySlugIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListPendingTeamInvitationsByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListPendingTeamInvitationsByIDIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListPendingTeamInvitationsBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListPendingTeamInvitationsBySlugIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamMembersByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListTeamMembersByIDIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamMembersBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListTeamMembersBySlugIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamReposByIDIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListTeamReposByIDIter(context.Background(), 0, 0, nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamReposBySlugIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListTeamReposBySlugIter(context.Background(), "", "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListTeamsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestTeamsService_ListUserTeamsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Teams.ListUserTeamsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListAllIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListAllIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListBlockedUsersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListBlockedUsersIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListEmailsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListEmailsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListFollowersIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListFollowersIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListFollowingIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListFollowingIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListGPGKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListGPGKeysIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListInvitationsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListInvitationsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListKeysIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListPackagesIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListPackagesIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListSSHSigningKeysIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListSSHSigningKeysIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListSocialAccountsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListSocialAccountsIter(context.Background(), nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}

func TestUsersService_ListUserSocialAccountsIter(t *testing.T) {
	t.Parallel()
	client, mux, _ := setup(t)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, `[]`)
	})

	ctx := context.Background()
	_ = ctx // avoid unused

	// Call iterator with zero values
	iter := client.Users.ListUserSocialAccountsIter(context.Background(), "", nil)
	for _, err := range iter {
		if err != nil {
			t.Errorf("Unexpected error: %v", err)
		}
	}
}
